package it.snorcini.dev.patternrecognition.dto;

import it.snorcini.dev.patternrecognition.error.PatternRecognitionValidationErrors;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.validation.annotation.Validated;

/**
 * DTO used for a Point creation.
 * <p>
 * Methods are auto-generated by Lombok.
 * <p>
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
@Validated
public class PointDTO {

    @NotNull(message = PatternRecognitionValidationErrors.COORDINATE_NULL)
    protected Double x;

    @NotNull(message = PatternRecognitionValidationErrors.COORDINATE_NULL)
    protected Double y;

}
