package it.snorcini.dev.patternrecognition.dto;

import jakarta.validation.Valid;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.experimental.SuperBuilder;

import java.util.List;

/**
 * DTO returned to the caller, contains the delivery plan..
 * <p>
 * Methods are auto-generated by Lombok.
 * <p>
 * This class @extends {@link PatternRecognitionBaseResponse} contains
 * generic response data.
 */
@SuperBuilder
@Data
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@NoArgsConstructor
public class SegmentsListResponse extends PatternRecognitionBaseResponse {

    /**
     * The segments.
     */
    @Valid
    private List<LineDTO> segments;

}
